version: '3.8'  # Versión de Docker Compose
services:
  pa_db:
    container_name: pa_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      #cambiar el usuario defaut de admin a root
      # MYSQL_USER_FILE: /run/secrets/db_user
      # MYSQL_PASSWORD_FILE: /run/secrets/db_password
    # secrets:
      # - db_root_password
      # - db_password
      # - db_user

    ports:
      - "3306:3306"
    volumes: #volúmenes anónimos o bind mount.
      - ${PROJECT_PATH}:/var/lib/mysql
    
    restart: no
    networks:
      - red-pa
networks:
  red-pa:
    driver: bridge

# secrets:
#   db_root_password:
#     file: db_root_password.txt
  # db_password:
  #   file: db_password.txt
  # db_user:
  #   file: db_user.txt
volumes:
    db_data: